name: Check commit message format

on: [workflow_call]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '25'

      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Run commitlint
        run: |
          commitlint --from "$FROM" --to "$TO" --verbose
        env:
          FROM: ${{ github.event.pull_request.base.sha }}
          TO: ${{ github.event.pull_request.head.sha }}
