name: Run code quality checks

on: [workflow_call]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: 'Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run directory lint
        run: pnpm ls-lint

      - name: Run prettier (only check)
        run: pnpm format:check

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run lint
        run: pnpm lint
